/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_certh_iti_haptics_NativePhantomManager */

#ifndef _Included_com_certh_iti_haptics_NativePhantomManager
#define _Included_com_certh_iti_haptics_NativePhantomManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_certh_iti_haptics_NativePhantomManager
 * Method:    Initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_certh_iti_haptics_NativePhantomManager_Initialize
  (JNIEnv *, jclass);

/*
 * Class:     com_certh_iti_haptics_NativePhantomManager
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_certh_iti_haptics_NativePhantomManager_close
  (JNIEnv *, jclass);

/*
 * Class:     com_certh_iti_haptics_NativePhantomManager
 * Method:    Update
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_certh_iti_haptics_NativePhantomManager_Update
  (JNIEnv *, jclass);

/*
 * Class:     com_certh_iti_haptics_NativePhantomManager
 * Method:    LoadModel
 * Signature: (Ljava/lang/String;DDD)I
 */
JNIEXPORT jint JNICALL Java_com_certh_iti_haptics_NativePhantomManager_LoadModel
  (JNIEnv *, jclass, jstring, jdouble, jdouble, jdouble);

/*
 * Class:     com_certh_iti_haptics_NativePhantomManager
 * Method:    moveModel
 * Signature: (Ljava/lang/String;DDD)I
 */
JNIEXPORT jint JNICALL Java_com_certh_iti_haptics_NativePhantomManager_moveModel
  (JNIEnv *, jclass, jstring, jdouble, jdouble, jdouble);

/*
 * Class:     com_certh_iti_haptics_NativePhantomManager
 * Method:    removeModel
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_certh_iti_haptics_NativePhantomManager_removeModel
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_certh_iti_haptics_NativePhantomManager
 * Method:    increaseModelSize
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_certh_iti_haptics_NativePhantomManager_increaseModelSize
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_certh_iti_haptics_NativePhantomManager
 * Method:    decreaseModelSize
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_certh_iti_haptics_NativePhantomManager_decreaseModelSize
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_certh_iti_haptics_NativePhantomManager
 * Method:    clearModels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_certh_iti_haptics_NativePhantomManager_clearModels
  (JNIEnv *, jclass);

/*
 * Class:     com_certh_iti_haptics_NativePhantomManager
 * Method:    moveMapLeft
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_certh_iti_haptics_NativePhantomManager_moveMapLeft
  (JNIEnv *, jclass);

/*
 * Class:     com_certh_iti_haptics_NativePhantomManager
 * Method:    moveMapRight
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_certh_iti_haptics_NativePhantomManager_moveMapRight
  (JNIEnv *, jclass);

/*
 * Class:     com_certh_iti_haptics_NativePhantomManager
 * Method:    moveMapUp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_certh_iti_haptics_NativePhantomManager_moveMapUp
  (JNIEnv *, jclass);

/*
 * Class:     com_certh_iti_haptics_NativePhantomManager
 * Method:    moveMapDown
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_certh_iti_haptics_NativePhantomManager_moveMapDown
  (JNIEnv *, jclass);

/*
 * Class:     com_certh_iti_haptics_NativePhantomManager
 * Method:    moveMapForward
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_certh_iti_haptics_NativePhantomManager_moveMapForward
  (JNIEnv *, jclass);

/*
 * Class:     com_certh_iti_haptics_NativePhantomManager
 * Method:    moveMapBack
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_certh_iti_haptics_NativePhantomManager_moveMapBack
  (JNIEnv *, jclass);

/*
 * Class:     com_certh_iti_haptics_NativePhantomManager
 * Method:    testRotMatrix
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_certh_iti_haptics_NativePhantomManager_testRotMatrix
  (JNIEnv *, jclass);

/*
 * Class:     com_certh_iti_haptics_NativePhantomManager
 * Method:    getObjNameInCollisionWithPhantom
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_certh_iti_haptics_NativePhantomManager_getObjNameInCollisionWithPhantom
  (JNIEnv *, jclass);

/*
 * Class:     com_certh_iti_haptics_NativePhantomManager
 * Method:    resetPhantomPosition
 * Signature: (DD)I
 */
JNIEXPORT jint JNICALL Java_com_certh_iti_haptics_NativePhantomManager_resetPhantomPosition
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     com_certh_iti_haptics_NativePhantomManager
 * Method:    createObj
 * Signature: ([[DI[[IILjava/lang/String;DI[I[[I)I
 */
JNIEXPORT jint JNICALL Java_com_certh_iti_haptics_NativePhantomManager_createObj
  (JNIEnv *, jclass, jobjectArray, jint, jobjectArray, jint, jstring, jdouble, jint, jintArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
